### ISSUE TITLE
`import pyvkfft.cuda` fail

### ISSUE THREAD

**Issue by t20100** [conda-forge/pyvkfft-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

With a fresh python3.11 environment, running `import pyvkfft.cuda` fail (tested on `ppc64le`) with the following exception:

<details><summary>Logs:</summary>

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pyvkfft.cuda

File lib/python3.11/site-packages/pyvkfft/cuda.py:31
     28 from .base import load_library, VkFFTApp as VkFFTAppBase, check_vkfft_result, ctype_int_size_p
     30 try:
---> 31     _vkfft_cuda = load_library("_vkfft_cuda")
     34     class _types:
     35         """Aliases"""

File lib/python3.11/site-packages/pyvkfft/base.py:120, in load_library(basename)
    118 else:
    119     ext = sysconfig.get_config_var('EXT_SUFFIX')
--> 120 return ctypes.cdll.LoadLibrary(os.path.join(os.path.dirname(__file__) or os.path.curdir, basename + ext))

File lib/python3.11/ctypes/__init__.py:454, in LibraryLoader.LoadLibrary(self, name)
    453 def LoadLibrary(self, name):
--> 454     return self._dlltype(name)

File lib/python3.11/ctypes/__init__.py:376, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    373 self._FuncPtr = _FuncPtr
    375 if handle is None:
--> 376     self._handle = _dlopen(self._name, mode)
    377 else:
    378     self._handle = handle

OSError: lib/python3.11/site-packages/pyvkfft/_vkfft_cuda.cpython-311-powerpc64le-linux-gnu.so: cannot open shared object file: No such file or directory
```

</details>

The `_vkfft_cuda.cpython-311-powerpc64le-linux-gnu.so` lib does not seems to be embedded in the generated package.

### Installed packages

```shell
The whole list is huge, I just put here relevant packages:

cuda-version              11.7                 h67201e3_2    conda-forge
cudatoolkit               11.7.1              hfcf6255_12    conda-forge
psutil                    5.9.5           py311hd26027c_1    conda-forge
pyvkfft                   2023.2          py311ha0a0dec_1    conda-forge
```

### Environment info

```shell
shell level : 1
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=ppc64le
                          __cuda=11.7=0
                          __glibc=2.31=0
                          __linux=5.4.0=0
                          __unix=0=0
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-ppc64le
                          https://conda.anaconda.org/conda-forge/noarch
               platform : linux-ppc64le
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.4.0-155-generic ubuntu/20.04.6 glibc/2.31
                UID:GID : 80583:3401
             netrc file : None
           offline mode : False
```

**Comment by vincefn** [comment]
Yes, the `py311ha0a0dec_1` has the following depends: `libgcc-ng >=12, libstdcxx-ng >=12, numpy, ocl-icd >=2.3.1,<3.0a0, psutil, pyopencl, python >=3.11,<3.12.0a0, python_abi 3.11.* *_cp311` which indicates that it does not support cuda.

The `py311h22e369c_1` has the tags: `__cuda >=11.2,<12, libgcc-ng >=12, libstdcxx-ng >=12, numpy, ocl-icd >=2.3.1,<3.0a0, psutil, pyopencl, python >=3.11,<3.12.0a0, python_abi 3.11.* *_cp311`

so this should be the correct version to support cuda.

Indeed using:
`mamba install pyvkfft=2023.2=py311h22e369c_1`

the import of pyvkfft.cuda works.

However I agree this is not intuitive - @isuruf or @jakirkham do you have suggestion as to how specify to install the pyvkfft package with the proper cuda support ? Should we use a label for the builds ?

**Comment by isuruf** [comment]
We can have the non-CUDA build conflict with `cuda-version` so that when `cuda-version` is installed, you get pyvkfft with CUDA support.

**Comment by jakirkham** [comment]
Noticing that we have these lines here

https://github.com/conda-forge/pyvkfft-feedstock/blob/683616ac1fca4dc9a42f227e358a1fec26fb869a/recipe/meta.yaml#L42-L46

<br>

Though no such line for CUDA 12 even though it was migrated

https://github.com/conda-forge/pyvkfft-feedstock/blob/683616ac1fca4dc9a42f227e358a1fec26fb869a/.ci_support/migrations/cuda120.yaml#L48

<br>

This may be tangential to the issue described here. Though it is an issue. So wanted to raise it for awareness (and in the small chance there is a relationship between the two issues)

**Comment by vincefn** [comment]
Thanks for looking into this with #20 (and #21). I added #22 to try to separate the cuda toolkit 11.2 and 11.8 builds.

However if I try (on x86) `mamba create -n testenv --no-banner python=3.11 pyvkfft --dry-run` I get pyvkfft `py311h71825b7_4` which has a constraint `cudatoolkit >=12.0` and depends `__cuda >=12.0,<13.0a0`? I guess due to the fact the system has the cuda draiver 12.1, and this is what `__cuda` reports.

But if I had pycuda `mamba create -n testenv --no-banner python=3.11 pyvkfft=2023.2 pycuda --dry-run` then I get `pyvkfft py311h2c5c81a_3` (from the previous build) with `cudatoolkit-11.8.0-h4ba93d1_12`, which is not right.

If I understand the depends/constrain system, `__cuda` corresponds to the detected cuda driver version. But then that seem too harsh - we need a strict constraint against the cudatoolkit (the nvrtc version), but as long as the driver is more recent we should be fine (I use pyvkfft pip-installed against cuda-toolkit 11.7 and this works with the driver 11.8, 12.1, etc..).

So this seems too strict:
```
 run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - __cuda >={{ cuda_compiler_version }},<11.8  # [cuda_compiler_version == '11.2']
    - __cuda >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.8']
    {% if cuda_major >=12 %}
    - __cuda >={{ cuda_compiler_version }},<{{ cuda_major + 1 }}.0a0
    {% endif %}
  run_constrained:
    - __cuda <0.0a0  # [cuda_compiler_version == "None"]
    - cudatoolkit =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - cudatoolkit >={{ cuda_compiler_version }},<11.8  # [cuda_compiler_version == '11.2']
    - cudatoolkit >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.8']
    {% if cuda_major >=12 %}
    - cudatoolkit >={{ cuda_compiler_version }},<{{ cuda_major + 1 }}.0a0
    {% endif %}
```

Maybe change this to:

```
 run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda >={{ cuda_compiler_version }}
  run_constrained:
    - cudatoolkit <0.0a0  # [cuda_compiler_version == "None"]
    - cudatoolkit =={{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
```

or (to only pin the cudatoolkit to X.Y):
```
 run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda >={{ cuda_compiler_version }}
  run_constrained:
    - cudatoolkit <0.0a0  # [cuda_compiler_version == "None"]
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [cuda_compiler_version != "None"]
```

Or should we use `cuda-version` (note to self, see https://github.com/conda-forge/cuda-version-feedstock/issues/1#issuecomment-1462998398).
Fernando, let me know what you, I'm a little beyond my conda skills...

**Comment by vincefn** [comment]
Ok, using #23 which just relaxes the `__cuda` depends, I get, when trying on x86 with the cuda driver 12.1 (`mamba info` says `__cuda=12.1=0`):

* `mamba create -n testenv --no-banner python=3.10 pyvkfft=2023.2 cuda-version=11.8 pycuda`
  *  installs pyvkfft `py310h70a93da_5` tagged with `cudatoolkit >=11.8,<12` OK
  * pyvkfft-test seems to pass
* `mamba create -n testenv --no-banner python=3.10 pyvkfft=2023.2 cuda-version=11.2 pycuda`
  *  installs pyvkfft `py310hbe3ad0c_5` tagged with `cudatoolkit >=11.2,<11.8` OK
  * pyvkfft-test seems to pass

Testing on an x86 machine without cuda:
* `mamba create -n testenv --no-banner python=3.10 pyvkfft=2023.2 pyopencl` => pyvkfft `py310h11dbdba_5` with constrain `__cuda <0.0a0` => also OK

So this should be OK... I'll test ppc64le tomorrow

**Comment by isuruf** [comment]
Looks good to me.

**Comment by t20100** [comment]
Works for me!
Thanks!
